### ISSUE TITLE
dateWeekStart

### ISSUE THREAD

**Issue by ton252** [belkevich/nsdate-calendar#10]
I have problem with Russian calendar and the first day of the week. For example, today is 20.03.2016, ENG first week day is 1 and RUS is 2. 
With your expression:  components.day -= components.weekday - [NSCalendar.currentCalendar firstWeekday]
1)ENG: dateWeekStart = 20 - (1-1) = 20.03.2016 - correct.
2)RUS: dateWeekStart = 20 - (1-2) = 21.03.2016  - incorrect

**Comment by belkevich** [comment]
Unfortunately, `NSCalendar.currentCalendar.firstWeekday` is always sunday, even you use russian locale. And you unable to change 'firstWeekday' property.
I thought about 'custom calendar' property of 'NSDate' and use it in date components calculations. What do you thinks about it?

**Comment by ton252** [comment]
Are you sure, that `NSCalendar.currentCalendar.firstWeekday` return always Sunday? Did try to change  your regional settings in your simulator (Settings > General >Language&Region>Region Format )? Because for me, it return 2(Monday ). For me the easiest way is something like this:
```
- (NSArray *)dateWeekLimits{
    
    NSCalendar *calendar = [NSCalendar currentCalendar];
    NSDate *now = self;
    NSDate *startWeek;
    NSDate *endWeek;
    NSTimeInterval interval;
    [calendar rangeOfUnit:NSCalendarUnitWeekOfYear
                startDate:&startWeek
                 interval:&interval
                  forDate:now];
    
    endWeek = [startWeek dateByAddingTimeInterval:interval-1];
    
    return @[startWeek, endWeek];
}
```

**Comment by belkevich** [comment]
Ok, I'll test it

**Comment by belkevich** [comment]
I've changed 'Region' to 'Russia' in iPhone Simulator.
Here is my code:
```objective-c
NSDate *date = [NSDate date]; // 29.03.16
NSLog(@"\nweek start: %@\nweek end: %@\n", date.dateWeekStart, date.dateWeekEnd);
```
And here is output:
```
week start: 2016-03-27 21:00:00 +0000
week end: 2016-04-02 21:00:00 +0000
```

So, for my locale (Ukraine, UTC+3) I'll get 2016-03-28 00:00:00 and 2016-04-03 00:00:00 respectively.

**Comment by ton252** [comment]
Yes, that's right. But did try to test your method with Sunday? The problem appear only for the last day of the week. Change your date, for example to 27.03.2016(Sunday) and try again. You will see, that the result dates will be for next week. Сheck carefully the boundary days

**Comment by belkevich** [comment]
@ton252, sorry, for delay.
I see. It's a very strange behavior. Here this my code (in Swift):

```Swift
let formatter = NSDateFormatter()
formatter.dateFormat = "dd-MM-y HH:mm:ss";
let date = formatter.dateFromString("05-06-2016 19:26:44")!
print("\nweek start: \(date.dateWeekStart())\nweek end: \(date.dateWeekEnd())\n")
```
And output is:
```
week start: 2016-06-05 21:00:00 +0000
week end: 2016-06-11 21:00:00 +0000
```

I need time to find out the solution.

**Comment by belkevich** [comment]
@ton252 
Looks like I've fixed it.
[Release 0.0.9](https://git.io/vonmA)
